category_patterns_dict = {'breast tenderness': [r'(breast(?:s)?|boob(?:s)?) (hurt|(is|are) (sore|sensitive|tender))',
                                                r'soreness of (breast(?:s)?|boob(?:s)?)',
                                                r'(tender|sore|sensitive) (breast(?:s)?|boob(?:s)?)',
                                                r'(breast(?:s)?|boob(?:s)?) pain'],
                        'nausea': ['nausea', 
                                   'naseuous', 
                                   'sick to my stomach', 
                                   'queasy', 
                                   'vomit', 
                                   'throw up', 
                                   'puke',
                                   'puking'],
                        'skin conditions': ['skin is clearing up', 
                                            'breaking out',
                                            'broke out',
                                            'break out',
                                            'acne', 
                                            'pimples', 
                                            'melasma'], 
                        'menstrual bleeding': ['spotting',
                                               'breakthrough bleed',
                                               'bleed nonstop',
                                               'period nonstop',
                                               'nonstop period',
                                               'bled for six months',
                                               'heavy period',
                                               r'period(?:s)? (became|is|are) (regular|heavy|light|irregular)',
                                               'missed period',
                                               'missed my period'
                                               'skipped period',
                                               'skipped my period',
                                               'no period',
                                               'bleed',
                                               'heavy period',
                                               'light period'], 
                        'weight & appetite': [r'(gain(?:ed)?|lost|lose) a (couple|few) pounds', 
                                              r'(gain(?:ed)?|lost|lose) weight',
                                              r'(gain(?:ed)?|lost|lose) [a-z0-9]+ (pounds|kilograms|lb|lbs|kg|stone)'
                                              'appetite',
                                              'craving',
                                              'hungry'],
                        'mental health': ['anxiety', 
                                          'mood', 
                                          'depression', 
                                          'depressed', 
                                          'anxious', 
                                          'anxiety',
                                          'mental health', 
                                          'panic attack', 
                                          'irritable', 
                                          'irritability',
                                          'emotional'], 
                        'sex drive': ['sex drive', 
                                      'sexual drive',
                                      'libido'],
                        'bloating': ['bloat',
                                     'water retention'],
                        'sleep': ['sleepy', 
                                  'can\'t sleep', 
                                  'tired all the time', 
                                  'always feel tired', 
                                  'exhausted',
                                  'fatigue', 
                                  'always tired'], 
                        'pms': ['pms'],
                        'hair loss': ['hair loss',
                                      'hair fell',
                                      'hair thinning',
                                      'bald',
                                      'hair fall',
                                      'hair shed'],
                        'headache': ['headache', 
                                     'head hurt',
                                     'head ache'],
                        'migraine': ['migraine'],
                        'infection': ['infection', 
                                      'uti'], # careful, need to search for token not any string containing (maybe do this for any target with fewer than X characters)
                        'severe effects': ['blood clot', 
                                           'pulmonary embolism', 
                                           'stroke',
                                           'heart attack'],
                        'vaginal discharge': ['discharge'],
                        'dryness': ['lubricat', 'dryness', 'wet'],
                        'pain': ['painful', 
                                 'pain', 
                                 'hurt',
                                 'agony',
                                 'cramp',
                                 'throb',
                                 'stabbing',
                                 'stabbed',
                                 'ache'], # will include headache but that's ok? should we also include 'tender', 'sensitive' which will include breast sensitivity?
                        'partner felt strings': [r'(partner|husband|boyfriend|bf|he|they) (could feel|felt) the strings'],
                        'general side effects': ['side effect']}